### PR TITLE
chore(462): update dependencies & add GitHub Action

### PR DESCRIPTION
**Pull request by meganesu**

### CODE REVIEW

**Review by mabuyo — APPROVED** [review]
Let's merge this one first and see how the workflow goes for the next couple days before tackling the rest of the starter code repos. What do you think @meganesu ?

Though I would like to get the `react-scripts` update out for folks sooner, we've had a couple messages popping up around that issue.

**Comment by meganesu** [comment]
@mabuyo I've got PRs up for the other repos too (linked in the ticket), but it includes both the updates and the new GitHub Action. I found one little bug in the GitHub Action that I wanna fix across all those repos, but it should be a quick copy-paste fix. Thinking we can merge them in later today, if that works for you!

**Comment by mabuyo** [comment]
@meganesu Sorry by "tackling the rest" I meant merging the work you'd already done! Can we merge this one, let the GH action run and confirm it works before merging the rest?

**Comment by meganesu** [comment]
Oh yeah totally! I'll merge it now 🥳

**Pull request merged**
